In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
from sklearn.model_selection import train_test_split

In [83]:
df=pd.read_csv(r'C:\Users\ALbayan\Desktop\AS_Tm\price_car\train_set_.csv')
df.head()

  ID;Name;Location;Year;Kilometers_Driven;Fuel_Type;Transmission;Owner_Type;Mileage;Engine;Power;Seats;Price
0  0;Maruti Wagon R LXI CNG;Mumbai;2010;72000;CNG...
1  1;Hyundai Creta 1.6 CRDi SX Option;Pune;2015;4...
2  2;Honda Jazz V;Chennai;2011;46000;Petrol;Manua...
3  3;Maruti Ertiga VDI;Chennai;2012;87000;Diesel;...
4  4;Audi A4 New 2.0 TDI Multitronic;Coimbatore;2...

In [84]:
df[['ID', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'Price']] = df['ID;Name;Location;Year;Kilometers_Driven;Fuel_Type;Transmission;Owner_Type;Mileage;Engine;Power;Seats;Price'].str.split(';', expand=True)
df.drop('ID;Name;Location;Year;Kilometers_Driven;Fuel_Type;Transmission;Owner_Type;Mileage;Engine;Power;Seats;Price', axis=1, inplace=True)
df.head()
df.info

<bound method DataFrame.info of         ID                              Name    Location  Year  \
0        0            Maruti Wagon R LXI CNG      Mumbai  2010
1        1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015
2        2                      Honda Jazz V     Chennai  2011
3        3                 Maruti Ertiga VDI     Chennai  2012
4        4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
...    ...                               ...         ...   ...
5843  6014                  Maruti Swift VDI       Delhi  2014
5844  6015          Hyundai Xcent 1.1 CRDi S      Jaipur  2015
5845  6016             Mahindra Xylo D4 BSIV      Jaipur  2012
5846  6017                Maruti Wagon R VXI     Kolkata  2013
5847  6018             Chevrolet Beat Diesel   Hyderabad  2011

     Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage   Engine  \
0                72000       CNG       Manual      First  26.6 km/kg   998 CC
1                41000    Diesel       Manual      First  19.67 kmpl  1582 CC
2                46000    Petrol       Manual      First   18.2 kmpl  1199 CC
3                87000    Diesel       Manual      First  20.77 kmpl  1248 CC
4                40670    Diesel    Automatic     Second   15.2 kmpl  1968 CC
...                ...       ...          ...        ...         ...      ...
5843             27365    Diesel       Manual      First   28.4 kmpl  1248 CC
5844            100000    Diesel       Manual      First   24.4 kmpl  1120 CC
5845             55000    Diesel       Manual     Second   14.0 kmpl  2498 CC
5846             46000    Petrol       Manual      First   18.9 kmpl   998 CC
5847             47000    Diesel       Manual      First  25.44 kmpl   936 CC

          Power Seats  Price
0     58.16 bhp   5.0   1.75
1     126.2 bhp   5.0   12.5
2      88.7 bhp   5.0    4.5
3     88.76 bhp   7.0    6.0
4     140.8 bhp   5.0  17.74
...         ...   ...    ...
5843     74 bhp   5.0   4.75
5844     71 bhp   5.0    4.0
5845    112 bhp   8.0    2.9
5846   67.1 bhp   5.0   2.65
5847   57.6 bhp   5.0    2.5

[5848 rows x 13 columns]>

In [85]:
df_without_ID=df.drop('ID', axis=1)
df_without_ID.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.5
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.5
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74

In [86]:
df_without_ID['Mileage'] = pd.to_numeric(
    df_without_ID['Mileage'].astype(str).str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)

df_without_ID['Engine'] = pd.to_numeric(
    df_without_ID['Engine'].astype(str).str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)

df_without_ID['Power'] = pd.to_numeric(
    df_without_ID['Power'].astype(str).str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)
df_without_ID['Seats'] = pd.to_numeric(
    df_without_ID['Seats'].astype(str).str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)
df_without_ID['Seats'] .astype('float64').fillna(df_without_ID['Seats'].mean(), inplace=True)
df_without_ID['Year'] = pd.to_numeric(df_without_ID['Year'], errors='coerce').astype('float64')
df_without_ID['Kilometers_Driven'] = pd.to_numeric(df_without_ID['Kilometers_Driven'], errors='coerce').astype('float64')
df_without_ID.info()
df_without_ID.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5848 entries, 0 to 5847
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5848 non-null   object
 1   Location           5848 non-null   object
 2   Year               5848 non-null   float64
 3   Kilometers_Driven  5848 non-null   float64
 4   Fuel_Type          5848 non-null   object
 5   Transmission       5848 non-null   object
 6   Owner_Type         5848 non-null   object
 7   Mileage            5846 non-null   float64
 8   Engine             5813 non-null   float64
 9   Power              5707 non-null   float64
 10  Seats              5807 non-null   float64
 11  Price              5848 non-null   object
dtypes: float64(6), object(6)
memory usage: 548.4+ KB

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010.0,72000.0,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015.0,41000.0,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.5
2,Honda Jazz V,Chennai,2011.0,46000.0,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.5
3,Maruti Ertiga VDI,Chennai,2012.0,87000.0,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013.0,40670.0,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74

In [87]:
print(df_without_ID.isnull().sum())

Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                2
Engine                35
Power                141
Seats                 41
Price                  0
dtype: int64

In [88]:
for col in ['Mileage','Engine','Power','Seats']:
    df[col] = df[col].fillna(df[col].mode()[0])

In [89]:
df_without_ID = pd.get_dummies(
    df_without_ID,
    columns=['Location', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Name'],
    drop_first=True
)
df_without_ID.head()

,Year,Kilometers_Driven,Mileage,Engine,Power,Seats,Price,Location_Bangalore,Location_Chennai,Location_Coimbatore,...,Name_Volvo S80 D5,Name_Volvo V40 Cross Country D3,Name_Volvo V40 D3,Name_Volvo V40 D3 R Design,Name_Volvo XC60 D4 SUMMUM,Name_Volvo XC60 D4 Summum,Name_Volvo XC60 D5,Name_Volvo XC60 D5 Inscription,Name_Volvo XC90 2007-2015 D5 AT AWD,Name_Volvo XC90 2007-2015 D5 AWD
0,2010.0,72000.0,26.60,998.0,58.16,5.0,1.75,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2015.0,41000.0,19.67,1582.0,126.20,5.0,12.5,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2011.0,46000.0,18.20,1199.0,88.70,5.0,4.5,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,2012.0,87000.0,20.77,1248.0,88.76,7.0,6.0,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,2013.0,40670.0,15.20,1968.0,140.80,5.0,17.74,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [90]:
X = df_without_ID.drop('Price', axis=1)   
y = df_without_ID['Price']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,      
    random_state=42    
)

In [91]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [92]:
print(X_train.select_dtypes(include='object').columns)

Index([], dtype='object')

In [93]:
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [94]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4678, 1831)
(1170, 1831)
(4678,)
(1170,)